name: Scrape

# controls when the workflow will run
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cach: true
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: uv sync
      - name: Run scraper
        run: uv run pierce.py
